DELETE http://localhost:3003/api/blogs/62ce97910a07b6cb847c98e4
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hc2kiLCJpZCI6IjYyY2U4MzhhMDUxNmVmNzJlZWNhMTI3NCIsImlhdCI6MTY1NzczMDc1MCwiZXhwIjoxNjU3NzM0MzUwfQ.LZEVd-UKkqheJpGdQaLVMPL33nGarKu4LoW4h96bJoE